project:
  type: website
  render:
    - "*.qmd"
  resources:
    - CNAME

website:
  title: "Cryptography & Software Engineering"
  description: "Cryptography & Software Engineering"
  site-url: https://rkiy.dev
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  page-footer:
    center: "Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    right:
      - icon: github
        href: https://github.com/rkiyanchuk
      - icon: linkedin
        href: https://linkedin.com/in/rkiyanchuk

format:
  html:
    theme: litera

execute:
  freeze: auto
